name: Buildpacks

on:
  push:
    branches:
      - develop  # Cambia esto según la rama deseada

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Paso 1: Chequea el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Verifica si Docker está instalado
      - name: Check Docker installation
        run: docker --version

      # Paso 3: Build
      - name: Build Docker image using buildpacks
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}          
          docker build -t ghcr.io/runongrid/front:${IMAGE_TAG} -f .docker/Dockerfile .           

      # Paso 4: Inicia sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_HUB_USERNAME }}
          password: ${{ secrets.GIT_HUB_TOKEN }}

      # Paso 5: Taggins de imagenes
      - name: Taggins Images
        run:  |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag ghcr.io/runongrid/front:${IMAGE_TAG} ghcr.io/runongrid/front:latest

      # Paso 6: Publica la imagen al registro
      - name: Push Docker image
        run:  |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push ghcr.io/runongrid/front:${IMAGE_TAG}
          docker push ghcr.io/runongrid/front:latest

  deploy-dev:
    runs-on: ubuntu-24.04
    needs: build  
    
    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          cd gridcloud-infra-repository/
          git pull
          docker-compose pull
          docker-compose up -d